// <auto-generated />
using System;
using ForecastingGas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace forecastingGas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250823153213_added timeComputed")]
    partial class addedtimeComputed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ForecastingGas.Data.Entities.ActualValues", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ActualValue")
                        .HasColumnType("decimal(18,9)");

                    b.Property<int>("DataDescriptionID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DataDescriptionID");

                    b.ToTable("GetActualValues");
                });

            modelBuilder.Entity("ForecastingGas.Data.Entities.DataDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateUploaded")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GetDataDescriptions");
                });

            modelBuilder.Entity("ForecastingGas.Data.Entities.ErrorValues", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlgoType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateEvaluated")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MAE")
                        .HasColumnType("decimal(18,9)");

                    b.Property<decimal>("MAPE")
                        .HasColumnType("decimal(18,9)");

                    b.Property<decimal>("MSE")
                        .HasColumnType("decimal(18,9)");

                    b.Property<double>("RMSE")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("GetErrorValues");
                });

            modelBuilder.Entity("ForecastingGas.Data.Entities.ForecastDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlgoType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ForecastDate")
                        .HasColumnType("datetime2");

                    b.PrimitiveCollection<string>("LevelValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeasonLength")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("SeasonalValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeComputed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalCount")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("TrendValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GetForecastDescriptions");
                });

            modelBuilder.Entity("ForecastingGas.Data.Entities.ForecastValues", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ForecastDescriptionID")
                        .HasColumnType("int");

                    b.Property<decimal>("ForecastValue")
                        .HasColumnType("decimal(18,9)");

                    b.HasKey("Id");

                    b.HasIndex("ForecastDescriptionID");

                    b.ToTable("GetForecastValues");
                });

            modelBuilder.Entity("ForecastingGas.Data.Entities.PredictionValues", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ForecastDescriptionID")
                        .HasColumnType("int");

                    b.Property<decimal>("PredictionValue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ForecastDescriptionID");

                    b.ToTable("GetPredictionValues");
                });

            modelBuilder.Entity("ForecastingGas.Data.Entities.ActualValues", b =>
                {
                    b.HasOne("ForecastingGas.Data.Entities.DataDescription", "GetDataDescription")
                        .WithMany("ActualValues")
                        .HasForeignKey("DataDescriptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GetDataDescription");
                });

            modelBuilder.Entity("ForecastingGas.Data.Entities.ForecastValues", b =>
                {
                    b.HasOne("ForecastingGas.Data.Entities.ForecastDescription", "GetForecastDescription")
                        .WithMany("GetForecastValues")
                        .HasForeignKey("ForecastDescriptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GetForecastDescription");
                });

            modelBuilder.Entity("ForecastingGas.Data.Entities.PredictionValues", b =>
                {
                    b.HasOne("ForecastingGas.Data.Entities.ForecastDescription", "GetForecastDescription")
                        .WithMany("GetPredictionValues")
                        .HasForeignKey("ForecastDescriptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GetForecastDescription");
                });

            modelBuilder.Entity("ForecastingGas.Data.Entities.DataDescription", b =>
                {
                    b.Navigation("ActualValues");
                });

            modelBuilder.Entity("ForecastingGas.Data.Entities.ForecastDescription", b =>
                {
                    b.Navigation("GetForecastValues");

                    b.Navigation("GetPredictionValues");
                });
#pragma warning restore 612, 618
        }
    }
}
