// <auto-generated />
using System;
using ForecastingGas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace forecastingGas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250906062342_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ForecastingGas.Data.Entities.ActualValues", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ActualValue")
                        .HasColumnType("decimal(38,9)");

                    b.Property<int>("DataDescriptionID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DataDescriptionID");

                    b.ToTable("GetActualValues");
                });

            modelBuilder.Entity("ForecastingGas.Data.Entities.DataDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateUploaded")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GetDataDescriptions");
                });

            modelBuilder.Entity("ForecastingGas.Data.Entities.ErrorValues", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlgoType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateEvaluated")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MAE")
                        .HasColumnType("decimal(18,9)");

                    b.Property<decimal>("MAE2")
                        .HasColumnType("decimal(18,9)");

                    b.Property<decimal>("MAE3")
                        .HasColumnType("decimal(18,9)");

                    b.Property<decimal>("MAPE")
                        .HasColumnType("decimal(18,9)");

                    b.Property<decimal>("MAPE2")
                        .HasColumnType("decimal(18,9)");

                    b.Property<decimal>("MAPE3")
                        .HasColumnType("decimal(18,9)");

                    b.Property<decimal>("MSE")
                        .HasColumnType("decimal(18,9)");

                    b.Property<decimal>("MSE2")
                        .HasColumnType("decimal(18,9)");

                    b.Property<decimal>("MSE3")
                        .HasColumnType("decimal(18,9)");

                    b.Property<double>("RMSE")
                        .HasColumnType("float");

                    b.Property<double>("RMSE2")
                        .HasColumnType("float");

                    b.Property<double>("RMSE3")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("GetErrorValues");
                });

            modelBuilder.Entity("ForecastingGas.Data.Entities.ForecastDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlgoType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("AlphaHwes")
                        .HasColumnType("float");

                    b.Property<double>("AlphaSes")
                        .HasColumnType("float");

                    b.Property<double>("Beta")
                        .HasColumnType("float");

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ForecastDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Gamma")
                        .HasColumnType("float");

                    b.Property<int>("SeasonLength")
                        .HasColumnType("int");

                    b.Property<string>("TimeComputed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalCount")
                        .HasColumnType("int");

                    b.Property<bool>("isLogTransformed")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("GetForecastDescriptions");
                });

            modelBuilder.Entity("ForecastingGas.Data.Entities.ForecastValues", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ForecastDescriptionID")
                        .HasColumnType("int");

                    b.Property<decimal>("ForecastValue")
                        .HasColumnType("decimal(18,9)");

                    b.HasKey("Id");

                    b.HasIndex("ForecastDescriptionID");

                    b.ToTable("GetForecastValues");
                });

            modelBuilder.Entity("ForecastingGas.Data.Entities.PredictionValues", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ForecastDescriptionID2")
                        .HasColumnType("int");

                    b.Property<decimal>("PredictionValue")
                        .HasColumnType("decimal(18,9)");

                    b.HasKey("Id");

                    b.HasIndex("ForecastDescriptionID2");

                    b.ToTable("GetPredictionValues");
                });

            modelBuilder.Entity("ForecastingGas.Data.Entities.PredictionValues2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ForecastDescriptionID3")
                        .HasColumnType("int");

                    b.Property<decimal>("PredictionValue2")
                        .HasColumnType("decimal(18,9)");

                    b.HasKey("Id");

                    b.HasIndex("ForecastDescriptionID3");

                    b.ToTable("GetPredictionValues2");
                });

            modelBuilder.Entity("ForecastingGas.Data.Entities.PredictionValues3", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ForecastDescriptionID4")
                        .HasColumnType("int");

                    b.Property<decimal>("PredictionValue3")
                        .HasColumnType("decimal(18,9)");

                    b.HasKey("Id");

                    b.HasIndex("ForecastDescriptionID4");

                    b.ToTable("GetPredictionValues3");
                });

            modelBuilder.Entity("ForecastingGas.Data.Entities.ActualValues", b =>
                {
                    b.HasOne("ForecastingGas.Data.Entities.DataDescription", "GetDataDescription")
                        .WithMany("ActualValues")
                        .HasForeignKey("DataDescriptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GetDataDescription");
                });

            modelBuilder.Entity("ForecastingGas.Data.Entities.ForecastValues", b =>
                {
                    b.HasOne("ForecastingGas.Data.Entities.ForecastDescription", "GetForecastDescription")
                        .WithMany("GetForecastValues")
                        .HasForeignKey("ForecastDescriptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GetForecastDescription");
                });

            modelBuilder.Entity("ForecastingGas.Data.Entities.PredictionValues", b =>
                {
                    b.HasOne("ForecastingGas.Data.Entities.ForecastDescription", "GetForecastDescription2")
                        .WithMany("GetPredictionValues")
                        .HasForeignKey("ForecastDescriptionID2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GetForecastDescription2");
                });

            modelBuilder.Entity("ForecastingGas.Data.Entities.PredictionValues2", b =>
                {
                    b.HasOne("ForecastingGas.Data.Entities.ForecastDescription", "GetForecastDescription3")
                        .WithMany("GetPredictionValues2")
                        .HasForeignKey("ForecastDescriptionID3")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GetForecastDescription3");
                });

            modelBuilder.Entity("ForecastingGas.Data.Entities.PredictionValues3", b =>
                {
                    b.HasOne("ForecastingGas.Data.Entities.ForecastDescription", "GetForecastDescription3")
                        .WithMany("GetPredictionValues3")
                        .HasForeignKey("ForecastDescriptionID4")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GetForecastDescription3");
                });

            modelBuilder.Entity("ForecastingGas.Data.Entities.DataDescription", b =>
                {
                    b.Navigation("ActualValues");
                });

            modelBuilder.Entity("ForecastingGas.Data.Entities.ForecastDescription", b =>
                {
                    b.Navigation("GetForecastValues");

                    b.Navigation("GetPredictionValues");

                    b.Navigation("GetPredictionValues2");

                    b.Navigation("GetPredictionValues3");
                });
#pragma warning restore 612, 618
        }
    }
}
