// <auto-generated />
using System;
using ForecastingGas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace forecastingGas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260331101655_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ForecastingGas.Data.Entities.ActualValues", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ActualValue")
                        .HasColumnType("numeric(38,9)");

                    b.Property<int>("DataDescriptionID")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DataDescriptionID");

                    b.ToTable("GetActualValues");
                });

            modelBuilder.Entity("ForecastingGas.Data.Entities.DataDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateUploaded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("GetDataDescriptions");
                });

            modelBuilder.Entity("ForecastingGas.Data.Entities.ErrorValues", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AlgoType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateEvaluated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ForecastDescriptionIdError")
                        .HasColumnType("integer");

                    b.Property<decimal>("MAE")
                        .HasColumnType("numeric(18,9)");

                    b.Property<decimal>("MAE2")
                        .HasColumnType("numeric(18,9)");

                    b.Property<decimal>("MAE3")
                        .HasColumnType("numeric(18,9)");

                    b.Property<decimal>("MAPE")
                        .HasColumnType("numeric(18,9)");

                    b.Property<decimal>("MAPE2")
                        .HasColumnType("numeric(18,9)");

                    b.Property<decimal>("MAPE3")
                        .HasColumnType("numeric(18,9)");

                    b.Property<decimal>("MSE")
                        .HasColumnType("numeric(18,9)");

                    b.Property<decimal>("MSE2")
                        .HasColumnType("numeric(18,9)");

                    b.Property<decimal>("MSE3")
                        .HasColumnType("numeric(18,9)");

                    b.Property<double>("RMSE")
                        .HasColumnType("double precision");

                    b.Property<double>("RMSE2")
                        .HasColumnType("double precision");

                    b.Property<double>("RMSE3")
                        .HasColumnType("double precision");

                    b.Property<bool>("isLogTransformed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ForecastDescriptionIdError");

                    b.ToTable("GetErrorValues");
                });

            modelBuilder.Entity("ForecastingGas.Data.Entities.ForecastDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AlgoType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("AlphaHwes")
                        .HasColumnType("double precision");

                    b.Property<double>("AlphaSes")
                        .HasColumnType("double precision");

                    b.Property<double>("Beta")
                        .HasColumnType("double precision");

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ForecastDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Gamma")
                        .HasColumnType("double precision");

                    b.Property<int>("SeasonLength")
                        .HasColumnType("integer");

                    b.Property<string>("TimeComputed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer");

                    b.Property<bool>("isLogTransformed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("GetForecastDescriptions");
                });

            modelBuilder.Entity("ForecastingGas.Data.Entities.ForecastValues", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ForecastDescriptionID")
                        .HasColumnType("integer");

                    b.Property<decimal>("ForecastValue")
                        .HasColumnType("numeric(18,9)");

                    b.HasKey("Id");

                    b.HasIndex("ForecastDescriptionID");

                    b.ToTable("GetForecastValues");
                });

            modelBuilder.Entity("ForecastingGas.Data.Entities.PredictionValues", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ForecastDescriptionID2")
                        .HasColumnType("integer");

                    b.Property<decimal>("PredictionValue")
                        .HasColumnType("numeric(18,9)");

                    b.HasKey("Id");

                    b.HasIndex("ForecastDescriptionID2");

                    b.ToTable("GetPredictionValues");
                });

            modelBuilder.Entity("ForecastingGas.Data.Entities.PredictionValues2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ForecastDescriptionID3")
                        .HasColumnType("integer");

                    b.Property<decimal>("PredictionValue2")
                        .HasColumnType("numeric(18,9)");

                    b.HasKey("Id");

                    b.HasIndex("ForecastDescriptionID3");

                    b.ToTable("GetPredictionValues2");
                });

            modelBuilder.Entity("ForecastingGas.Data.Entities.PredictionValues3", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ForecastDescriptionID4")
                        .HasColumnType("integer");

                    b.Property<decimal>("PredictionValue3")
                        .HasColumnType("numeric(18,9)");

                    b.HasKey("Id");

                    b.HasIndex("ForecastDescriptionID4");

                    b.ToTable("GetPredictionValues3");
                });

            modelBuilder.Entity("ForecastingGas.Data.Entities.ActualValues", b =>
                {
                    b.HasOne("ForecastingGas.Data.Entities.DataDescription", "GetDataDescription")
                        .WithMany("ActualValues")
                        .HasForeignKey("DataDescriptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GetDataDescription");
                });

            modelBuilder.Entity("ForecastingGas.Data.Entities.ErrorValues", b =>
                {
                    b.HasOne("ForecastingGas.Data.Entities.ForecastDescription", "GetForecastDescription5")
                        .WithMany("GetErrorValues")
                        .HasForeignKey("ForecastDescriptionIdError")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GetForecastDescription5");
                });

            modelBuilder.Entity("ForecastingGas.Data.Entities.ForecastValues", b =>
                {
                    b.HasOne("ForecastingGas.Data.Entities.ForecastDescription", "GetForecastDescription")
                        .WithMany("GetForecastValues")
                        .HasForeignKey("ForecastDescriptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GetForecastDescription");
                });

            modelBuilder.Entity("ForecastingGas.Data.Entities.PredictionValues", b =>
                {
                    b.HasOne("ForecastingGas.Data.Entities.ForecastDescription", "GetForecastDescription2")
                        .WithMany("GetPredictionValues")
                        .HasForeignKey("ForecastDescriptionID2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GetForecastDescription2");
                });

            modelBuilder.Entity("ForecastingGas.Data.Entities.PredictionValues2", b =>
                {
                    b.HasOne("ForecastingGas.Data.Entities.ForecastDescription", "GetForecastDescription3")
                        .WithMany("GetPredictionValues2")
                        .HasForeignKey("ForecastDescriptionID3")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GetForecastDescription3");
                });

            modelBuilder.Entity("ForecastingGas.Data.Entities.PredictionValues3", b =>
                {
                    b.HasOne("ForecastingGas.Data.Entities.ForecastDescription", "GetForecastDescription4")
                        .WithMany("GetPredictionValues3")
                        .HasForeignKey("ForecastDescriptionID4")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GetForecastDescription4");
                });

            modelBuilder.Entity("ForecastingGas.Data.Entities.DataDescription", b =>
                {
                    b.Navigation("ActualValues");
                });

            modelBuilder.Entity("ForecastingGas.Data.Entities.ForecastDescription", b =>
                {
                    b.Navigation("GetErrorValues");

                    b.Navigation("GetForecastValues");

                    b.Navigation("GetPredictionValues");

                    b.Navigation("GetPredictionValues2");

                    b.Navigation("GetPredictionValues3");
                });
#pragma warning restore 612, 618
        }
    }
}
